# setarile pentru baza de date (spring boot face automat connection pool cu hikaricp din ele)
spring.datasource.url=jdbc:postgresql://localhost:5432/movies_db
spring.datasource.username=postgres
spring.datasource.password=1234

# setam portul pe care va rula serverul nostru web
server.port=8080